[DO-557] handle trailing slashes
exactpro/docs-toolkit pull request #42
Opened 2023-07-06 13:56 UTC by StanG4313

2023-07-06 16:04 UTC, StanG4313 commented on utils/wTrailingSlash.ts
> +}
Without undefined option I receive type error, that's why I decided to leave this option

2023-07-06 16:07 UTC, d0rich commented on utils/wTrailingSlash.ts
> +}
You still can handle this case outside of function. It seems in some cases input value can be undefined.

2023-07-06 16:24 UTC, StanG4313 commented on utils/wTrailingSlash.ts
> +}
OK, will try to find a decent work-around

2023-07-07 11:36 UTC, StanG4313 commented on utils/wTrailingSlash.ts
> +    const result = withTrailingSlash(str)
Renamed on next commit

2023-07-07 12:36 UTC, StanG4313 commented on utils/wTrailingSlash.ts
> +}
Now fixed

2023-07-07 13:26 UTC, d0rich requested changes

2023-07-07 13:26 UTC, d0rich commented on components/ep/layout/SurroundDocCard.vue
> +    "
There can be a shorten expression

> If doc._path is `undefined` provide `''` instead.

```suggestion
    :to="withTrailingSlash(doc._path ?? '')"
```

2023-07-07 13:47 UTC, d0rich approved these changes

2023-07-07 13:49 UTC, merged