[DO-599] prev/next buttons description customization
exactpro/docs-toolkit pull request #54
Opened 2023-08-04 06:18 UTC by d0rich

2023-08-04 08:04 UTC, StanG4313 commented
@d0rich , am I right that our custom descriptions will be limited with 2 lines of text? 
And also, should we create some documentation section/page to describe this feature for our users?

2023-08-04 09:24 UTC, d0rich commented
> @d0rich , am I right that our custom descriptions will be limited with 2 lines of text? And also, should we create some documentation section/page to describe this feature for our users?

Only descriptions in prev/next cards will be limited, if you specified `display: 'limited'`. By default it will remain full.

I think I will add some documentation.

2023-08-04 09:27 UTC, StanG4313 requested changes
It will be good after adding some documentation of this feature

2023-08-04 13:46 UTC, StanG4313 commented on docs/content/3.customization.md
> +         * 'limit' - display first n lines of description
```suggestion
         * 'limited' - display first n lines of description
```

With 'limit' it didn't changed

2023-08-07 09:42 UTC, StanG4313 approved these changes

2023-08-07 12:32 UTC, merged